# Disable Jekyll processing for GitHub Pages
plugins: []

# Include all necessary files
include:
  - .nojekyll
  - .htaccess
  - "*.js"
  - "*.mjs"
  - "*.json"
  - "*.css"
  - "assets/*"

# Exclude Jekyll processing files
exclude:
  - "*.md"
  - "*.yml" 
  - "*.yaml"

# Force proper MIME types
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS'
    'Access-Control-Allow-Headers': 'DNT,X-CustomHeader,Keep-Alive,User-Agent'

# Ensure proper MIME types for JavaScript files
mime_types:
  .js: "text/javascript"
  .mjs: "application/javascript"
  .json: "application/json"
  .css: "text/css"
  .mjs: "text/javascript"