plugins:
  - jekyll-optional-front-matter

include:
  - .nojekyll
  - "*.js"
  - "*.mjs"

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

kramdown:
  input: GFM

# Ensure proper MIME types for JavaScript files
mime_types:
  .js: "text/javascript"
  .mjs: "text/javascript"